### ISSUE TITLE
Vercel re-deploy on non-master branch's change ?

### ISSUE THREAD

**Issue by ctuanle** [Khanhtran47/react-movie#11]
@Khanhtran47 
Nãy thấy master có mấy commits mới của bot, merge về branch feature thì thấy vercel chạy task deploy, đáng lẽ ra chỉ chạy task này khi có thay đổi phía master thôi nhỉ?

**Comment by Khanhtran47** [comment]
@ctuanle rứa à, t nhớ setting trong vercel t bỏ có branch master rồi

**Comment by Khanhtran47** [comment]
@ctuanle à nếu mà merge về branch thì m merge từ develop ý với k cần tạo pull request mô, cứ git merge develop rứa

**Comment by Khanhtran47** [comment]
@ctuanle nếu mà thấy develop chưa update với master thì m merge luôn :v

**Comment by ctuanle** [comment]
@Khanhtran47 cái eslint nới xài sao vậy, có format code không ?, tạo format chung để code cho tiện

**Comment by Khanhtran47** [comment]
@ctuanle hồi xưa có cái eslint-prettier mà sao h tự nhiên thấy tụi prettier bỏ lm rồi, h k biết xài thằng nào nữa 😅

**Comment by ctuanle** [comment]
ừm, vậy để lúc nào thêm file .prettierrc

**Comment by ctuanle** [comment]
> @ctuanle hấn kiểu cái quy tắc code thôi, t mới để có mấy cái, bỏ nhiều sợ eslint với prettier nó xung đột với nhau

cần set up extension hay gì đó k?, thấy nỏ hiện gì cả

**Comment by Khanhtran47** [comment]
@ctuanle m tải extension sau chạy là đc, tại t mới cài mấy cái rule import, export bth thôi nên code bth k thấy mô :v
