### ISSUE TITLE
Add transition for header

### ISSUE THREAD

**Issue by Khanhtran47** [Khanhtran47/react-movie#28]
Add transition on opening/closing drawer for header

https://user-images.githubusercontent.com/54718468/174457803-0f5e6e61-313b-4277-ab81-fd24d03fb9d7.mp4

**Comment by Khanhtran47** [comment]
@ctuanle ủa m mở cái left drawer ra có bị lag k tuân, sao hồi t mở bth sao bữa ni lại thấy lag lag

**Comment by ctuanle** [comment]
@Khanhtran47 lag như thế nào t nhìn k ra nơi :v , transition ?

**Comment by Khanhtran47** [comment]
@ctuanle chắc do máy cty t cùi quá xem nó cứ lag lag :v

**Comment by ctuanle** [comment]
@Khanhtran47  t xem video của m đó cũng nhìn k ra :v 
Phần thụt vào có vẻ hơi nhanh ?

**Comment by Khanhtran47** [comment]
@ctuanle ừ cái ni đáng t phải bỏ transition cho thanh header nữa

**Comment by ctuanle** [comment]
@Khanhtran47  mà k biết m dùng code nào chứ thấy cái đó cũ rồi ấy

**Comment by Khanhtran47** [comment]
@ctuanle ừ cái ni t đăng từ 6 ngày trc rồi

**Comment by ctuanle** [comment]
@Khanhtran47  ra vậy :v, làm nãy giờ t xem video k hiểu lag ở mô, xem trên vercel cũng nỏ thấy

**Comment by Khanhtran47** [comment]
@ctuanle ừ hình như do máy cty t lag thôi
