### ISSUE TITLE
replace mui icon

### ISSUE THREAD

**Issue by Khanhtran47** [Khanhtran47/react-movie#29]
- [x] thay hết mui icon rồi remove mui với emotion 

t mới tìm đc cái ni, m bt thư viện mô có icon mô nhìn đc k ?
https://react-icons.github.io/react-icons

**Comment by Khanhtran47** [comment]
https://react-kawaii.vercel.app/#/React%20Kawaii này k phải icon đều nhìn cute :v

**Comment by ctuanle** [comment]
> @ctuanle https://react-kawaii.vercel.app/#/React%20Kawaii này k phải icon đều nhìn cute :v

cute thật :v, ngay cả trang docs cx cute nựa



> m bt thư viện mô có icon mô nhìn đc k ?

t cx ít khi mò bên UI nên cx k biết nựa, đều tìm thử thì ra mấy cái như này:
[npm-search](https://www.npmjs.com/search?q=react-icons*)
[blueprintjs](https://blueprintjs.com/docs/) (19.1k starts)
https://phosphoricons.com/

**Comment by Khanhtran47** [comment]
@ctuanle m muốn tải cả 1 thư viện luôn hay chỉ tải từng icon một cho tiết kiệm, nếu mà thư viện thì t thấy cái react-icons với blueprintjs nớ đc (blueprintjs ni hình như phải tải cả tool của hấn mới có icon thì phải), còn tải riêng lẻ từng cái, cần cái mô tải cái nớ thì xài trang ni https://icons8.com/icons/ hoặc https://iconscout.com/ t thấy ok nhất

**Comment by ctuanle** [comment]
@Khanhtran47  nếu chỉ để dùng trong cái menu thôi thì t nghĩ chắc tải từng cái cho khỏe :v

**Comment by Khanhtran47** [comment]
@ctuanle 

![image](https://user-images.githubusercontent.com/54718468/174487238-1597210d-4f43-4836-8967-49cda0beb9e2.png)

**Comment by Khanhtran47** [comment]
@ctuanle t nghĩ 3 cái đầu xài đc nhất rồi, ionicons, hero icons, phosphor icons

**Comment by ctuanle** [comment]
@Khanhtran47 oke
