### ISSUE TITLE
Film trending banner 

### ISSUE THREAD

**Issue by Khanhtran47** [Khanhtran47/react-movie#6]
Maybe take data from db like this, but we create a card banner from next-ui (or mui) like in the design :v
https://nextui.org/docs/components/card
https://mui.com/material-ui/react-card/

![image](https://user-images.githubusercontent.com/54718468/172071605-59511ff4-e89b-4b87-97b0-5bd252ee666b.png)

![image](https://user-images.githubusercontent.com/54718468/172071651-2f2fc2fd-4595-498b-b2c0-c0e3080800c9.png)
source pic: dribble

**Comment by Khanhtran47** [comment]
@ctuanle call api chắc xài axios hậy, hay react query

**Comment by ctuanle** [comment]
@Khanhtran47 fetch cho khỏe :v, đỡ phải cài thêm dependency

**Comment by Khanhtran47** [comment]
@ctuanle fetch ajax á, cái nớ call ngu lắm, nó quản lý response cứ đụt đụt kiểu gì ấy :v
k kiểu để thống nhất xài chi trc để t tạo file call bên api

**Comment by Khanhtran47** [comment]
@ctuanle t nghĩ là tạo 1 issue config cái api trc rồi lại lm mấy issue ni

**Comment by ctuanle** [comment]
@Khanhtran47 
> fetch ajax á,

k phải ajax, hàm fetch built-in cơ

> t nghĩ là tạo 1 issue config cái api trc rồi lại lm mấy issue ni

m xem cái commit https://github.com/Khanhtran47/react-movie/commit/9e7a3180e4651ad0049a1b2bdd4c7e86fc4aea6c ni thử có ok không ?

**Comment by Khanhtran47** [comment]
@ctuanle ừ hàm fetch bth của react đó, hấn kiểu ban đầu xài thì đc đc sau đôi khi nó cứ kiểu thiếu thiếu ý, m thử xài axios đi, hấn kiểu tự động convert data đc với có xử lý lỗi nữa

**Comment by ctuanle** [comment]
@Khanhtran47 thấy mình chỉ dùng để get từng request riêng lẻ thì thấy k khác nhau mấy, convert thì res.json() là ra, xử lí lỗi thì t nghĩ giống nhau cả thôi, catch lỗi r xử lí. Mà muốn dùng axios thì cũng đc, thấy cx k khác nhau lắm

**Comment by Khanhtran47** [comment]
@ctuanle k m cứ xài fetch trước đi, khi mô merge vô rồi t lm tiếp t đổi sang axios sau

**Comment by Khanhtran47** [comment]
@ctuanle m muốn xài redux luôn k, hay context api đc rồi :v

**Comment by ctuanle** [comment]
@Khanhtran47  t nghĩ dùng gì cũng đc :v

Mà cx tùy xem muốn dùng để lưu chi nữa, nếu đơn giản ít update thì dùng context đỡ phải cài thêm đồ, nếu không thì dùng redux cho tiện

**Comment by Khanhtran47** [comment]
@ctuanle nghĩ là chỉ lưu mấy cái kiểu setting cơ bản của ng dùng với của app thui (dark/light mode, theme app, user info, mấy hàm để dịch nếu thêm đa ngôn ngữ, ...)
chắc sau khi #7, #5 xong thì mình xài context trc rồi sau này setup lại redux sau

**Comment by ctuanle** [comment]
@Khanhtran47  ok

**Comment by Khanhtran47** [comment]
@ctuanle m tạo PR đi rồi t xem

**Comment by Khanhtran47** [comment]
@ctuanle t mới tạo 1 branch beta, m code đc từng mô cứ merge vô cái branch ni rồi test nha 
https://react-movie-git-beta-khanhtran47.vercel.app/

**Comment by Khanhtran47** [comment]
@ctuanle issue ni t lm tiếp nha

**Comment by ctuanle** [comment]
@Khanhtran47  oke

**Comment by ctuanle** [comment]
@Khanhtran47 
![image](https://user-images.githubusercontent.com/70543626/179931352-d19642d8-2300-48fe-8b3d-5865d2178636.png)

chỗ trang trending hình như bị lệch sang bên trái ý

**Comment by ctuanle** [comment]
@Khanhtran47  ok



> ủa mà sao m lại hiện cái scroll nơi left drawer rứa :v

à do t co ngắn cái cửa sổ lại thôi
