### ISSUE TITLE
Test authentication

### ISSUE THREAD

**Issue by Khanhtran47** [Khanhtran47/react-movie#7]
Maybe using back for creating db for user :v

**Comment by ctuanle** [comment]
what to save in db ?
- [ ]  favourite film?
- [ ]  account info?
- [ ]  what else ?

**Comment by Khanhtran47** [comment]
ừ favorite film, film đang xem, account info, account setting (theme, color...)

**Comment by ctuanle** [comment]
nên dùng kiểu database nào nhỉ? Mongodb, redis, firebase, hay là mysql, postgresql :v

**Comment by Khanhtran47** [comment]
@ctuanle này thì t chịu nơi, m thạo cái chi hay muốn test cái mới thì cứ quẩy thôi 😂

**Comment by Khanhtran47** [comment]
@ctuanle https://github.com/clerkinc/remix-bossa-nova-stack auth mình xài supabase với của cái ni đk

**Comment by ctuanle** [comment]
@Khanhtran47  okay, dùng cho mỗi auth thôi hay sao ?

**Comment by Khanhtran47** [comment]
@ctuanle ừ kiểu để đăng nhập với get thông tin user trước, với có cái database để test, xài cho hết api của remix 😅

**Comment by ctuanle** [comment]
@Khanhtran47 okey, làm issue này trước hay đợi app hoạt động ổn định rồi mới làm cái này ?

**Comment by Khanhtran47** [comment]
@ctuanle m lm giờ cũng đc, tối về t lm cái dark mode rồi sau m thử thêm cái theme ng dùng chọn vô nơi thông tin user chọn thử

**Comment by ctuanle** [comment]
@Khanhtran47 okei

**Comment by ctuanle** [comment]
@Khanhtran47 
Hiện tại dùng clerk ở dev thì khỏe (#42).
Còn nếu muốn dùng production thì phải có domain riêng (theo t đọc thì vậy) để trỏ về domain của clerk mới được.

**Comment by Khanhtran47** [comment]
@ctuanle rứa k xài clerk đc à m 🥲

**Comment by ctuanle** [comment]
@Khanhtran47  cũng được
đều k thấy nó chỉ so sánh mật khẩu chỗ mô nơi, hoặc t k hiểu session based auth :v

**Comment by Khanhtran47** [comment]
@ctuanle có tuto để xem lm theo cho dễ hiểu k hậy

**Comment by Khanhtran47** [comment]
@ctuanle https://github.com/mitchelvanbever/remix-auth-supabase :v

**Comment by ctuanle** [comment]
@Khanhtran47 cái này có vẻ hợp lí hơn cái trước :v

**Comment by ctuanle** [comment]
@Khanhtran47 
![image](https://user-images.githubusercontent.com/70543626/179370530-e606a2dd-ae9a-4243-958d-326ec259adaf.png)
well, nói vậy ai dám dùng lâu dài :v

**Comment by Khanhtran47** [comment]
@ctuanle 
https://blog.openreplay.com/implementing-authentication-in-remix-applications-with-supabase
https://dev.to/aaronksaunders/remix-authentication-using-remix-auth-package-2obl
https://www.youtube.com/watch?v=-KiH8feOHSc&ab_channel=AaronSaunders
https://codegino.com/blog/remix-supabase-auth

**Comment by Khanhtran47** [comment]
@ctuanle t search remix auth with supabase ra mấy cái tuto ni

**Comment by ctuanle** [comment]
@Khanhtran47  ừm để t xem thử

**Comment by Khanhtran47** [comment]
@ctuanle bên example của remix cũng có auth với supabase 
https://github.com/remix-run/remix/tree/main/examples/remix-auth-supabase
